yolo_model:

  config_file:
    name: yolov3-custom.cfg
  weight_file:
    name: yolov3-custom_4000.backup
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Bottle
      - Cup
      - Pringles
      - Sugar
