way_points: {
    frame: "map",
    search_one: {
        x: -0.5,
        y: 0.0,
        z: 0.0,
        w: 1.0
    },
    search_two: {
        x: 1.63,
        y: -0.6,
        z: 0.0,
        w: 1.0
    },
    drop_Bottle: {
        x: -2.45,
        y: 0.8,
        z: 0.0,
        rx: 0.0,
        ry: 0.0,
        rz: 0.7071,
        rw: 0.7071
    },
    drop_Cup: {
        x: -2.27,
        y: -0.78,
        z: 0.0,
        rx: 0.0,
        ry: 0.0,
        rz: -0.7071,
        rw: 0.7071 
    },
    drop_Pringles: {
        x: -2.64,
        y: 0.0,
        z: 0.0,
        rx: 0.0,
        ry: 0.0,
        rz: 1.0,
        rw: 0.0
    }
}